### PR TITLE
Add Meteor.js support

### PR DESCRIPTION
**Pull request by mediatainment**
Hi abpetkov,

I'm a Meteor.js dev and volunteer package maintainer for Meteor. Switchery is a great library, and adding it to Meteor's ecosystem will expose it to many new devs (Meteor has 22k+ stars on GitHub), likely bringing in new testers and contributors.

This PR will let you directly publish updated versions of the library as they become available. All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer.

I've already published the current version of the package on Atmosphere (Meteor's package directory / https://atmospherejs.com/abpetkov/switchery). When you release new versions, you can publish them to Atmosphere with grunt meteor automatically.

Thanks & best regards,
Jan

### CODE REVIEW

**Comment by abpetkov** [comment]
Cool, thanks for this awesome contribution, @mediatainment ! I've already registered, my username is `apetkov`, so if you could add me as maintainer that would be awesome.

Cheers.

**Comment by mediatainment** [comment]
of course :-) Thank you too!

Your username was added to switchery @ meteor devs

**Comment by abpetkov** [comment]
@mediatainment What is a good way to publish a new version of the package? I'm not using Grunt or Gulp and I don't intend to start using them for Meteor support only. Is there any command I can use in my Makefile that will go straight and push the new release?

**Comment by abpetkov** [comment]
@mediatainment Nevermind. I did that using the `meteor publish` command after I bumped the version in `package.js`.

**Pull request merged**
